name = "FTB Presents SkyFactory 2.5"
author = "Darkosto"
version = "2.5.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9c4a60bd9402f5b568c187288fb82c58c3a35c3968aacecd8b49aa421ebd947"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
