name = "FTB Presents SkyFactory 2.5"
author = "Darkosto"
version = "2.5.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de3f8a180c422b2e7f4ff0c7059e5f4037cbc5a7379ca78188a8f16191c4f6a5"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
